print('Ведите по порядку через Enter  5 этапов развития человека')
a1 = input('1 этап -')
a2 = input('2 этап -')
a3 = input('3 этап -')
a4 = input('4 этап -')
a5 = input('5 этап -')
print('Ответ:')
print( a1, a2, a3, a4, a5, sep='=>')
